name: Build

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install documentation generator
      run: npm install -g documentation
    - name: Install bundler
      run: npm install -g rollup
    - name: Install dependencies
      run: npm install
    - name: Build
      run: build/main.sh
    - name: Build documentation
      run: npm run docs
    - name: Bundle
      run: npm run bundle
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
