name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        registry-url: https://registry.npmjs.org/
    - name: Install dependencies
      run: npm ci
    - name: Prepare
      run: python prepare/main.py
    - name: Test
      run: npm test
    - name: Publish to npm
      shell: bash
      run: |
        if [[ "$IS_BETA" ]]; then
          npm publish --tag beta
        else
          npm publish
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_TSHET_UINH }}
        IS_BETA: ${{ github.event.release.prerelease && '1' || '' }}
